### PR TITLE
feat(yaml): add yaml support

### PR DESCRIPTION
**Pull request by fsx950223**
load model from yaml

### CODE REVIEW

**Comment by amir-abdi** [comment]
Thanks.
Please add a new flag for `input_model_yaml` and handle this decision more neatly. 
Don't rely on correct file extensions as this can cause confusion for the user.

**Comment by fsx950223** [comment]
> Thanks.
> Please add a new flag for `input_model_yaml` and handle this decision more neatly.
> Don't rely on correct file extensions as this can cause confusion for the user.

changed

**Comment by amir-abdi** [comment]
The `config` variable is not a good practice.
I will implement this feature myself.
Thank you for the suggestion.

**Comment by amir-abdi** [comment]
The feature is now added.

**Pull request closed without merging**
